services:
  db:
    image: postgres:16
    container_name: gym-ranker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gymrank
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data

